### ISSUE TITLE
Unicode regexes

### ISSUE THREAD

**Issue by MattDMo** [JoshuaWise/javascript-ultimate#1]
Hi Joshua,
@FichteFoll told me about your new JS syntax that supports Unicode characters. Since it's not on Package Control yet, I just cloned your repo so I could check it out, and it looks pretty cool. The reason I'm interested is two-fold - first, I maintain the [Neon Color Scheme](https://github.com/MattDMo/Neon-color-scheme) for Sublime, which tries to make as many languages as possible look as good as possible, so I am scanning your package to see if there are any specialized scopes I can add to Neon - more on that later.

Second, and more importantly, I'm the maintainer of the rather popular [PythonImproved](https://github.com/MattDMo/PythonImproved) syntax definition which, IMO (and those of many others) is loads better than the default `.tmLanguage` that ships with Sublime, and I'm always trying to improve that as well. One of my [issues](https://github.com/MattDMo/PythonImproved/issues/19) relates to matching Unicode identifiers in Python, which are perfectly legal, but not currently recognized. Since I haven't done any Unicode regexing before, I was wondering if you'd be willing to lend a hand.

As you're probably aware, Python identifiers must start with a letter (cap or lowercase) or underscore, but not a number. Subsequent characters (if any) can be any letter, number, or underscore. Right now, I'm using `[A-Za-z_][A-Za-z0-9_]*` (or some minor rearrangement) as the regex. Looking through JSUlt, I see a couple of patterns:

```
[\p{L}\p{Nl}$\p{Mn}\p{Mc}\p{Nd}\p{Pc}_\x{200C}\x{200D}]
([\p{L}\p{Nl}$_][\p{L}\p{Nl}$\p{Mn}\p{Mc}\p{Nd}\p{Pc}_\x{200C}\x{200D}]*+\s*+(\.)\s*+)*+([\p{L}\p{Nl}$_][\p{L}\p{Nl}$\p{Mn}\p{Mc}\p{Nd}\p{Pc}_\x{200C}\x{200D}]*+)
([\p{L}\p{Nl}$_][\p{L}\p{Nl}$\p{Mn}\p{Mc}\p{Nd}\p{Pc}_\x{200C}\x{200D}]*+)
```

and probably some others I missed. Basically, I need help translating the following:

```
[A-Za-z_]
[A-Za-z0-9_]
[A-Z_]
[A-Z_][A-Z0-9_]
```

Looking over the [Oniguruma definition](http://www.geocities.jp/kosako3/oniguruma/doc/RE.txt), I see that there are character classes such as `Alpha`, `Digit`, `Lower`, `Alnum`, etc. Is there any reason why you didn't use those, or any reason why I couldn't use them? In my mind, it would make the regexes much easier to interpret.

So, any help or inspiration you could provide would be great!

Thanks,
Matt

**Comment by FichteFoll** [comment]
I guess it generally depends on whether the "unicode case" applies or not. This would also tell if `\w` matches unicode or not, or vice versa. And then if there is an equivalent posix bracket for the `[\p{L}\p{Nl}$\p{Mn}\p{Mc}\p{Nd}\p{Pc}_\x{200C}\x{200D}]` and `[\p{L}\p{Nl}$_]` patterns.

Edit: It seems like that is the case, since `\p{Alpha}` and `\p{Alnum}` work very much as expected.

Edit2: more details in https://github.com/MattDMo/PythonImproved/issues/19

**Comment by JoshuaWise** [comment]
Hi Matt,
Thanks for reaching out to me.
The character classes you mentioned (Alpha, Digit, Lower, Alnum, etc.) don’t map directly to the Unicode property classes (\p{…}), and it’s these Unicode properties that are defined in the ECMAScript specification http://ecma-international.org/ecma-262/5.1/#sec-7.6 as being valid JavaScript identifiers.
The legal identifiers in Python are a bit different from in JavaScript. The rules for Python 3’s identifiers can be found here: https://docs.python.org/3/reference/lexical_analysis.html#identifiers https://docs.python.org/3/reference/lexical_analysis.html#identifiers

For Python 3, the regular expression you gave me can be translated to support Unicode as follows:

[A-Za-z_] = [\p{L}\p{Nl}_\x{2118}\x{212E}\x{309B}\x{309C}]

[A-Za-z0-9_] = [\p{L}\p{Nl}_\x{2118}\x{212E}\x{309B}\x{309C}\p{Mn}\p{Mc}\p{Nd}\p{Pc}\x{1369}\x{00B7}\x{0387}\x{19DA}]

[A-Z_] = [\p{Lu}\p{Lt}\p{Lo}\p{Lm}\p{Nl}_\x{2118}\x{212E}\x{309B}\x{309C}]

[A-Z0-9_] = [\p{Lu}\p{Lt}\p{Lo}\p{Lm}\p{Nl}_\x{2118}\x{212E}\x{309B}\x{309C}\p{Mn}\p{Mc}\p{Nd}\p{Pc}\x{1369}\x{00B7}\x{0387}\x{19DA}]

Yeah, it’s not very pretty, because Python allows some Unicode categories that don’t have direct representations within the Oniguruma definition.

Cheers!
Joshua Wise

**Comment by MattDMo** [comment]
Thanks for the help! I actually hadn't come across that page in the Python docs before, it's quite useful. Do you know of any resources that explain what `\p{Alnum}`, etc. actually map to in Oniguruma? Also, if you extensively tested your regexes, how did you do it? Do you know of any resources where we could get a selection of characters from each class (`\p{Lu}`, `\p{Lt}`, etc.) and test them against the more generic classes (`\p{Alpha}` etc.) that I'm currently using?

**Comment by JoshuaWise** [comment]
No problem, I’m glad I could help.
There are definitions for POSIX character classes (e.g. [:alnum:]) in the Oniguruma definition as well. Search for "6. Character class”.
It’s not clear whether [:alnum:] is equal to \p{Alnum}, but I think it would be reasonable to assume so.
The closest thing to matching:
[\p{L}\p{Nl}_\x{2118}\x{212E}\x{309B}\x{309C}\p{Mn}\p{Mc}\p{Nd}\p{Pc}\x{1369}\x{00B7}\x{0387}\x{19DA}]
would be:
[:word:]

but that’s still quite far from perfect. So if you care about readability in your language definition, I recommend Fitche’s idea:
[[[:word:]\p{Nl}]&&[^\p{Me}]]
Personally, I don’t care about readability that much, since I figure most people won’t be looking inside my language file anyways.
Cheers!
Joshua Wise
