### ISSUE TITLE
Damn uninstall 

### ISSUE THREAD

**Issue by vpArth** [JoshuaWise/javascript-ultimate#11]
Guys, I get your plugin from plugin list in Sublime.  
I think - let's try it. And my HTML highlighting was broken after it.. :(

Ok, let's uninstall it and things will be as were before...

But, for now I need to completely reinstall my Sublime.  JS highlight module even not exists now.

You should implement correct uninstallation.  
It just not ready to appear in public package list as is now.

**Comment by vpArth** [comment]
Ok, I found it inside ignored_packages.  
Javascript code inside HTML still white.

Why all of this can't be restored on uninstall?

**Comment by JoshuaWise** [comment]
Originally it was supposed to behave the way you expected, but when I developed this package there were bugs involved with the Sublime Text 3 API that I would've needed to use in order to have a proper uninstallation process. Those bugs might be fixed now, but I don't know for sure. This will be revisited when I rewrite the package in Sublime's new ".sublime-syntax" language format, as soon as it is available in the stable release versions of Sublime Text 3.

**Comment by vpArth** [comment]
assume it's abandoned

**Comment by JoshuaWise** [comment]
It's not abandoned. The `.sublime-syntax` was finally just released on a stable version of Sublime Text 3, so the new version of JavaScript Ultimate is now in development.

**Comment by vpArth** [comment]
Just half-year without commits, script's assumption. It's cool, good luck :)

**Comment by JoshuaWise** [comment]
With the newest version of JavaScript Ultimate, a rewrite of the install/uninstall scripts were done, and this issue has been resolved.
