### ISSUE TITLE
Comparison with babel-sublime

### ISSUE THREAD

**Issue by franciscolourenco** [JoshuaWise/javascript-ultimate#20]
How does this package compare to [babel-sublime](https://github.com/babel/babel-sublime)? 
Any advantages?

**Comment by JoshuaWise** [comment]
`javascript-ultimate` is the only syntax out there that highlights errors in your code. Usually if you type something that the syntax doesn't recognize, it will leave it unhighlighted, like a normal variable name. But `javascript-ultimate` actually traverses your code and highlights syntax errors with a "bad" color.

`javascript-ultimate` also follows the ES6 **spec** exactly, while most syntax plugins are just the author's understanding of the language and usually they miss edge cases in the language. `javascript-ultimate` also has pretty advanced regular expression comprehension.

**Comment by franciscolourenco** [comment]
@JoshuaWise would you say the only feature babel-sublime has over javascript-ultimate is support for JSX?

**Comment by JoshuaWise** [comment]
I haven't extensively studied babel-sublime, but I believe that assessment is likely to be true.

**Comment by bathos** [comment]
This is my first time coming across this definition and as the author of [Ecmascript Syntax](https://github.com/bathos/Ecmascript-Sublime), which operates similarly ("only syntax out there that highlights errors in your code" isn’t true, though it may be the case that this one does so better), I’m curious to know more about how they differ. If this covers all the same territory as ES Sublime (or if it could w/ some contributions), I would consider closing up shop on it in the interest of reducing fragmentation of tooling.

Some context re: ES Sublime —

- the main goal there was to provide much more specific scope targets than existing defs
- current with ES2018
- covers a number of proposed features (decorators, class properties, etc)
- covers JSX
- happens to mark many invalid tokens as invalid, but as a side effect of the approach rather than a key objective, which I think is a difference from the angle here
- follows the spec to _most_ of the extent that’s actually possible (a bit confused by "perfectly accurate" claim here — does this have a Python component to overcome the linebreak blindness constraint?), but in expressions does fall back on heuristics at a certain point (due to left recursion realities)
